# Generated by Django 2.2.16 on 2022-08-11 17:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_post_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='подписка на самого себя',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('user')), name='подписка на самого себя'),
        ),
    ]
